### ISSUE TITLE
use other net

### ISSUE THREAD

**Issue by Magiczhuu** [yifan123/IC-Conv#5]
May I use other networks, such as Unet, not resnet, how should I use Ic_con  and how to generate a pattern?

**Comment by yifan123** [comment]
Thanks for your interest in our work!

You can try to replace normal convolution in encoder with IC_conv.

First you should train a Unet with conv9*9 in encoder (as long as it's bigger than 3 \* 3). Then generate patterns as in our paper. 

To make it easier, you can first try setting the dilation scale manually. For example, in the first layer, dilation pattern (0, 0) accounts for 0.5, and other dilation patterns evenly divide the remaining 0.5. In the latter layer, dilation 0*0 accounts for 0.7, and other dilations divide the remaining 0.3 equally.

If you find the above manual pattern useful, consider using the method in our paper to search for better patterns.

Best
Jie

**Comment by Magiczhuu** [comment]
非常感谢您的回复。我是小白一枚，请问生成pattern是自己手动生成吗，有没有可以自动生成的程序呢？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jie ***@***.***&gt;; 
发送时间: 2021年7月29日(星期四) 晚上6:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yifan123/IC-Conv] use other net (#5)






感谢您对我们工作的关注！

你可以尝试用 IC _ conv 代替编码器中的普通卷积。

首先你应该用 conv 9 训练一个 Unet编码器* 9（只要大于 3 * 3 就行）。然后生成我们论文中的模式。

为了使它更容易，你可以先尝试手动设置扩张规模。例如，在第一层中，膨胀图案（ 0 , 0 ）占0.5，其他膨胀图案平均地除以剩余的0.5。在后一层中，膨胀 0 * 0 占0.7，其他的膨胀平分剩下的0.3。

如果您觉得上面的手动模式有用，可以考虑使用本文中的方法来搜索更好的模式。

最好的
介

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在 GitHub 上查看或取消订阅.
