### ISSUE TITLE
pattern_dist

### ISSUE THREAD

**Issue by lifanhanhan** [yifan123/IC-Conv#6]
How do I define this "pattern_dist" ,if I only use ICConv2d module.Thanks.

**Comment by CyunXiong** [comment]
I also want to ask this question ,how can I make a [ic_resnet34_k9.json]\[ic_resnet18_k9.json] by the way?

**Comment by yifan123** [comment]
The shallow and deep layers of the network require slightly different dilation. If you only want to use a single ICConv2d, I suggest simply manually setting the ratio of different dilation modes as described in the [comments]( https://github.com/yifan123/IC-Conv/issues/5#issuecomment-888985887). I look forward to ICConv2d providing performance improvements in your tasks.
