### ISSUE TITLE
The web of pretrained weights is 404

### ISSUE THREAD

**Issue by JiangMei0201** [yifan123/IC-Conv#7]
Thanks for your great repo.
The web of pretrained weights is 404.  I can't download the all pretrained checkpoints. Is there something wrong?
Looking for your reply.

**Comment by yifan123** [comment]
Thanks for you interesting for our work!

I just checked the link and it still works. Is it a network problem of your computer because this is a link from Google Drive.

**Comment by yifan123** [comment]
I updated a link of baidu drive in the readme. You are welcome to download and use it.

**Comment by JiangMei0201** [comment]
> 

Thanks a lot. I download it.
