### ISSUE TITLE
Inception Convolution with Efficient Dilation Search

### ISSUE THREAD

**Issue by MinghuiYao** [yifan123/IC-Conv#9]
Dr. Liu, I am reading your Inception Convolution with Efficient Dilation Search, the content is very well written, but about this convolution in the pattern parameters how to find the minimum representation error E, I have been puzzled, see the derivation of the last step in the formula with the L1 error of both weights Minimization, how is the weight obtained after that expansion, by training or some other way.
   Thank you very much if I can get your reply!

**Comment by yifan123** [comment]
Thank you very much for your attention to our work. 

I have already replied with specific details in the email you sent me. If you have any further questions, please feel free to ask.
